### ISSUE TITLE
std::__1::bad_function_call exception in ~Array when compiling with clang and linking with libc++

### ISSUE THREAD

**Issue by tamiko** [ginkgo-project/ginkgo#275]
As part of the deal.II testsuite we also test the freshly merged ginkgo wrappers. The ginkgo wrapper tests pass for all variants with gcc and libstdc++. Unfortunately, all test variants that use the clang compiler and LLVM's libc++ (in versions 4, 5, 6, or 7) fail [1] with a `std::__1::bad_function_call` exception. Stacktrace:

```
(gdb) bt
#0  0x00007fffd65db61b in raise () from /lib64/libc.so.6
#1  0x00007fffd65c4535 in abort () from /lib64/libc.so.6
#2  0x00007fffd1e831bf in ?? () from /usr/lib64/libc++abi.so.1
#3  0x00007fffd1e75e24 in ?? () from /usr/lib64/libc++abi.so.1
#4  0x00007fffd1e82636 in ?? () from /usr/lib64/libc++abi.so.1
#5  0x00007fffd1e82691 in std::terminate() () from /usr/lib64/libc++abi.so.1
#6  0x00007ffff29615bb in __clang_call_terminate () from /tmp/build/lib/libdeal_II.g.so.9.1.0-pre                                                                                             
#7  0x00007ffff660d39c in std::__1::unique_ptr<double [], std::__1::function<void (double*)> >::reset(decltype(nullptr)) (this=<optimized out>) at /usr/include/c++/v1/memory:2926            
#8  std::__1::unique_ptr<double [], std::__1::function<void (double*)> >::~unique_ptr() (this=<optimized out>) at /usr/include/c++/v1/memory:2869                                             
#9  gko::Array<double>::~Array (this=0x2895a0) at /usr/include/ginkgo/core/base/array.hpp:62
#10 0x00007ffff66165d8 in gko::matrix::Dense<double>::~Dense (this=0x2894e0) at /usr/include/ginkgo/core/matrix/sellp.hpp:51                                                                  
#11 0x00007ffff6616689 in gko::matrix::Dense<double>::~Dense (this=0x2894e0) at /usr/include/ginkgo/core/matrix/sellp.hpp:51                                                                  
#12 0x00007fffe9a09d53 in std::unique_ptr<gko::matrix::Dense<double>, std::default_delete<gko::matrix::Dense<double> > > gko::initialize<gko::matrix::Dense<double>>(unsigned long, std::initializer_list<gko::matrix::Dense<double>::value_type>, std::shared_ptr<gko::Executor const>) () from /usr/lib64/libginkgo.so                                                                     
#13 0x00007fffe9a09e80 in std::unique_ptr<gko::matrix::Dense<double>, std::default_delete<gko::matrix::Dense<double> > > gko::initialize<gko::matrix::Dense<double>>(std::initializer_list<gko::matrix::Dense<double>::value_type>, std::shared_ptr<gko::Executor const>) () from /usr/lib64/libginkgo.so                                                                                    
#14 0x00007fffe9bc4d3d in gko::solver::Cg<double>::apply_impl(gko::LinOp const*, gko::LinOp*) const () from /usr/lib64/libginkgo.so                                                           
#15 0x00007ffff660b4b2 in gko::LinOp::apply (this=0x2b5c00, b=<optimized out>, x=<optimized out>) at /usr/include/ginkgo/core/base/lin_op.hpp:146                                             
#16 0x00007ffff660c815 in dealii::GinkgoWrappers::SolverBase<double, int>::apply (this=0x7fffffffddb0, solution=..., rhs=...) at /srv/testsuite/dealii/source/lac/ginkgo_solver.cc:110        
#17 0x0000000000217bca in main (argc=<optimized out>, argv=<optimized out>) at /srv/testsuite/dealii/tests/ginkgo/solver.cc:62
```

I guess the issue lies somewhere in the custom deleter for `std::unique_ptr` as declared here (`ginkgo/core/base/array.hpp`):
```
436     using data_manager =
437         std::unique_ptr<value_type[], std::function<void(value_type[])>>;
```
But I haven't investigated any further whether the `default_deleter` goes out of scope too quickly or what exactly the issue is.

[1] https://cdash.kyomu.43-1.org/testSummary.php?project=1&name=ginkgo%2Fsolver.debug&date=2019-03-18

**Comment by tcojean** [comment]
Thanks for the report! This is interesting because we also test against pretty much all clang versions [see a recent pipeline](https://gitlab.com/ginkgo-project/ginkgo-public-ci/pipelines/52527161) but did not get that error. We'll see what is happening there.

**Comment by pratikvn** [comment]
@tamiko , I am not able to reproduce this error. I have the latest deal.ii repo on the master branch and the latest ginkgo develop branch. I compile both with clang-6.0 and all tests(ginkgo related) pass for me. Is there anything apart from the compiler being clang that is different in your clang test stages ? If you could share your CMakeCache.txt file, I could try to reproduce the same setup on my local system to reproduce the error. Thanks!

**Comment by tamiko** [comment]
Sorry for the noise. Culprit was very likely a misconfigured environment mixing both standard libraries.
